services:
  bpmn:
    image: zgl-repro
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PAIRS_CATALOG_CSV=assets/pairs-catalog-models.csv
    volumes:
      - ./results/:/app/results
