name: Run Experiment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-experiment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libatlas-base-dev gfortran

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Run experiment
        run: |
          echo "Starting experiment..."
          python run_experiment.py

      - name: Upload results
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: experiment-results
          path: output/

